"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const host_1 = require("@coglite/common/host");
const mobx_react_1 = require("mobx-react");
const React = require("react");
const AppRouter_1 = require("./AppRouter");
host_1.attachWindowMessaging(window);
const host = new host_1.BrowserAppHostModel();
host.setRoot(true);
host.setRouter(AppRouter_1.AppRouter);
host.setPublicPath('/');
host.window = window;
exports.AppHostRoot = mobx_react_1.observer(() => React.createElement(host_1.AppHostContainer, { host: host }));
