"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const models_1 = require("../../models");
const models_2 = require("../models");
const DashboardRemoveStore = new models_1.SupplierModel();
exports.DashboardRemoveStore = DashboardRemoveStore;
const DashboardListClearStore = new models_1.SupplierModel();
exports.DashboardListClearStore = DashboardListClearStore;
const DashboardAddStore = new models_2.DashboardAddModel();
exports.DashboardAddStore = DashboardAddStore;
const ComponentRemoveStore = new models_2.ComponentRemoveModel();
exports.ComponentRemoveStore = ComponentRemoveStore;
