// auth action types
export const AUTH_REGISTER_COMPLETE = 'AUTH_REGISTER_COMPLETE';
export const AUTH_GUEST_MODE = 'AUTH_GUEST_MODE';
export const AUTH_LOGOUT_COMPLETE = 'AUTH_LOGOUT_COMPLETE';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_CHECK = 'AUTH_CHECK';
export const AUTH_DEFAULT = 'AUTH_DEFAULT';

// profile action types
export const PROFILE_EMPTY = 'PROFILE_EMPTY';
export const PROFILE_VIEW = 'PROFILE_VIEW';

// global action types
export const GLOBAL_DEFAULT = 'GLOBAL_DEFAULT';
export const GLOBAL_GET_FRIEND_LIST = 'GLOBAL_GET_FRIEND_LIST';
export const GLOBAL_ADD_FRIEND_LIST = 'GLOBAL_ADD_FRIEND_LIST';
export const GLOBAL_ADD_GROUP_LIST = 'GLOBAL_ADD_GROUP_LIST';
export const GLOBAL_GET_GROUPS_LIST = 'GLOBAL_GET_GROUPS_LIST';

//Search action types
export const SET_SEARCH_LIST = 'SET_SEARCH_LIST';
export const GET_SEARCH_LIST = 'GET_SEARCH_LIST';
export const LOADING_STATUS = 'LOADING_STATUS';
export const RESET_USERS_LIST = 'RESET_USERS_LIST';
export const GET_USERS_LIST = 'GET_USERS_LIST';
export const RESET_GROUPS_LIST = 'RESET_GROUPS_LIST';
export const SET_USERS_LIST = 'SET_USERS_LIST';
export const GET_GROUPS_LIST = 'GET_GROUPS_LIST';
export const SET_GROUPS_LIST = 'SET_GROUPS_LIST';
export const CONNECT_REQUEST = 'CONNECT_REQUEST';
export const FRIEND_CONNECTED = 'FRIEND_CONNECTED';

// Layout action types
export const LAYOUT_TOGGLE_POPUP = 'LAYOUT_TOGGLE_POPUP';

// Messages action types
export const RESET_CONVERSATION = 'RESET_CONVERSATION';
export const RESET_GROUPS = 'RESET_GROUPS';
export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
export const ADD_CONVERSATION_MESSAGE = 'ADD_CONVERSATION_MESSAGE';
export const ADD_USER_IS_TYPING = 'ADD_USER_IS_TYPING';
export const ADD_TYPING_TEXT = 'ADD_TYPING_TEXT';
export const REMOVE_USER_IS_TYPING = 'REMOVE_USER_IS_TYPING';
export const UPDATE_CONVERSATION_STATUS = 'UPDATE_CONVERSATION_STATUS';
export const GROUP_MEMBERS = 'GROUP_MEMBERS';
export const CONVERSATION = 'CONVERSATION';
export const CURRENT_GROUP = 'CURRENT_GROUP';
export const CONVERSATION_LIST = 'CONVERSATION_LIST';
export const MESSAGES_GET_GROUPS_LIST = 'MESSAGES_GET_GROUPS_LIST';
export const ADD_GROUPS_LIST = 'ADD_GROUPS_LIST';
export const RESET_CURRENT_ROOM = 'RESET_CURRENT_ROOM';
export const CONVERSATION_MESSAGES = 'CONVERSATION_MESSAGES';
export const CONVERSATION_MESSAGES_LIST = 'CONVERSATION_MESSAGES_LIST';
export const CURRENT_ROOM = 'CURRENT_ROOM';
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';

// Notebook action types
export const CHANGE_CURRENT_FILE = 'CHANGE_CURRENT_FILE';
export const SOURCE_FILES = 'SOURCE_FILES';
export const FILE_PREVIEW = 'FILE_PREVIEW';
export const OUTPUT_LINE = 'OUTPUT_LINE';
export const UPDATE_NOTEBOOKS = 'UPDATE_NOTEBOOKS';
export const NEW_NOTEBOOK = 'NEW_NOTEBOOK';
export const ADD_NOTEBOOK_LINES = 'ADD_NOTEBOOK_LINES';
export const RESET_CURRENT_FILE = 'RESET_CURRENT_FILE';
export const EDIT_LINE = 'EDIT_LINE';
export const NEW_LINE = 'NEW_LINE';
export const EXPORT_DATA_FIELD = 'EXPORT_DATA_FIELD';
export const NEW_FILE = 'NEW_FILE';
export const SEND_NOTEBOOK_RECIPIENTS = 'SEND_NOTEBOOK_RECIPIENTS';
export const UPDATE_CURRENT_NOTEBOOK = 'UPDATE_CURRENT_NOTEBOOK';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const UPDATE_NEW_NOTEBOOKS = 'UPDATE_NEW_NOTEBOOKS';
export const DELETE_NOTEBOOK = 'DELETE_NOTEBOOK';
export const GET_ALERTS = 'GET_ALERTS';
export const NEW_ALERTS = 'NEW_ALERTS';

